---
settings:
  name: ONTAP FLI
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: ONTAP FLI Docs
      url: "/index.html"
    - title: Release Notes
      url: "/release-notes/whats-new-9171.html"
    - section: san-migration
    - title: Legal Notices
      url: /reference_legal_notices.html

product-family: 
  name: ONTAP
  repo: ontap-family



