---
permalink: san-migration/concept_best_practices_for_fli_migration.html
sidebar: sidebar
keywords: best practices, foreign lun, import migration
summary: "NetApp strongly recommends a professional services or partner professional services, engagement to scope and plan the migration as well as to train customer personnel on how to perform data migrations using Foreign LUN Import (FLI) 7-Mode to ONTAP."
---
= Best practices for Foreign LUN Import migration
:icons: font
:imagesdir: ../media/

[.lead]
NetApp strongly recommends a professional services or partner professional services, engagement to scope and plan the migration as well as to train customer personnel on how to perform data migrations using Foreign LUN Import (FLI) 7-Mode to ONTAP.

* Perform one or more test migrations at least a week prior to your migration project in order to verify configuration, connectivity, and throughput; uncover any other issues; and validate your methodology.
* For maximum throughput, don't run more than 16 migrations concurrently per node.
* Verification is not required, but we encourage you to verify a subset of the LUNs imported/migrated to validate the import process.
* Use the throughput observed in your test migrations to plan production migration durations.
* For best performance, migrate LUNs during non-peak demand periods.
