---
permalink: san-migration/concept_supported_host_operating_systems_for_fli_online.html
sidebar: sidebar
keywords: 
summary: 'The FLI online workflow can be used for LUNs connected to hosts running one of the following operating systems.'
---
= Supported host operating systems for FLI online
:icons: font
:imagesdir: ../media/

[.lead]
The FLI online workflow can be used for LUNs connected to hosts running one of the following operating systems.

. Microsoft (all versions of the servers listed are supported):
 ** Windows Server 2008 (includes Windows Server failover clusters)
 ** Microsoft Hyper-V server 2008
 ** Windows Server 2012 (includes Windows Server 2012 cluster)
 ** Microsoft Hyper-V Server 2012
. VMware:
 ** All ESXi 5.x releases
. Linux:
 ** Red Hat Enterprise Linux (RHEL) 5.x/6.x

Consider using the FLI offline workflow for host operating systems not on the preceding list.

[NOTE]
====
If the NetApp controller destination is a MetroCluster, do NOT use the online workflow. If a site failover occurred during an active online import, write pass-throughs to the source array could fail which would lead to a verification failure and potential data loss. If the destination is MetroCluster, use the FLI offline process, regardless of the host OS.
====
