---
permalink: san-migration/concept_foreign_lun_import_concepts.html
sidebar: sidebar
keywords: 
summary: 'Understanding of basic FLI concepts helps in proper operation and decreases the initial configuration effort.'
---
= Foreign LUN Import concepts
:icons: font
:imagesdir: ../media/

[.lead]
Understanding of basic FLI concepts helps in proper operation and decreases the initial configuration effort.

* *Foreign array*
+
A foreign array is a storage device that does not run ONTAP. This is also referred to as a third-party array or source array. In the case of a 7-Mode to ONTAP transition, the foreign array would be an array produced by NetApp running ONTAP 7-Mode.

* *Foreign LUN*
+
A foreign LUN is a LUN containing user data hosted on a third-party array using that array's native disk format.

* *FLI LUN relationship*
+
A FLI LUN relationship is a persistent pairing between source and destination storage for the purpose of data import. The source and destination endpoints are LUNs.

* *LUN import*
+
LUN import is a process of transferring the data in a foreign LUN from its third-party format into a native NetApp format LUN.
