---
permalink: san-migration/concept_fli_7_mode_to_ontap_transition_workflow.html
sidebar: sidebar
keywords: 
summary: 'This section provides an example of the FLI 7-Mode to ONTAP transition workflow. The transition workflow can be run as either an online or offline workflow.'
---
= FLI 7-Mode to ONTAP transition workflow
:icons: font
:imagesdir: ../media/

[.lead]
This section provides an example of the FLI 7-Mode to ONTAP transition workflow. The transition workflow can be run as either an online or offline workflow.

The FLI transition is recommended when either the source LUN is hosted on a 32-bit aggregate and/or the LUN is misaligned. The FLI 7-Mode to ONTAP transition is able to combine transitioning the LUN from 7-Mode to ONTAP, along with correcting LUN alignment and transitioning the LUN from a 32-bit to 64-bit aggregate. Other methods of transitioning the LUN, including 7-Mode Transition Tool (7MTT), can require remediating the LUN alignment and/or converting a 32-bit to 64-bit aggregate prior to transitioning to ONTAP.

The FLI 7-Mode to ONTAP transition workflow can be either an online or offline workflow. These workflows are functionally identical to the two corresponding FLI offline and online migration workflows, with the exception that the source array is a NetApp 7-Mode storage array. Both workflows share the same rules and procedures as their migration equivalents. This includes the FLI online workflow host operating support list.

The example provided should give a thorough walkthrough of the FLI 7-Mode to ONTAP process. The FLI 7-mode to ONTAP transition flow includes the following tasks:

. Preparing source and destination arrays
. Performing a disruptive cutover
. Importing the data
. Verifying migration results
. FLI transition post-migration tasks

*Related information*

xref:concept_supported_host_operating_systems_for_fli_online.adoc[Supported host operating systems for FLI online]
