---
permalink: san-migration/concept_fli_supported_configurations.html
sidebar: sidebar
keywords: 
summary: 'The FLI environment must be deployed in a supported manner to ensure proper operation and support. As engineering qualifies new configurations, the list of supported configurations will change. Refer to the NetApp Interoperability Matrix to verify support for specific configurations.'
---
= FLI supported configurations
:icons: font
:imagesdir: ../media/

[.lead]
The FLI environment must be deployed in a supported manner to ensure proper operation and support. As engineering qualifies new configurations, the list of supported configurations will change. Refer to the NetApp Interoperability Matrix to verify support for specific configurations.

ONTAP 8.3 and later are the only supported destination storage. Migrations to third-party storage are not supported.

For a list of supported source storage arrays, switches, and firmware, see the Interoperability Matrix. The data migration program will provide support for the configurations in the NetApp Interoperability Matrix.

Once the import is complete and all LUNs have been migrated to NetApp controllers, ensure that all configurations are supported.

*Related information*

https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]
