---
permalink: san-migration/concept_fli_offline_post_migration_tasks.html
sidebar: sidebar
keywords: fli, offline, post-migration, tasks
summary: "Any outstanding server remediation not performed earlier is performed during post-migration."
---
= Perform ONTAP FLI offline post-migration tasks
:icons: font
:imagesdir: ../media/

[.lead]
After you have completed your FLI offline migration, there are several post-migration tasks to perform.

.Steps

. Complete any server remediation not performed pre-migration.
. Review logs for errors
. link:configure-fc-adapter-target.html[Reset the host FC adapters to target mode].
. Verify that your host can access the LUNs on the NetApp storage.      
. Perform any application testing to verify that your migration completed cleanly and successfully.
. Remove any third-party software from the host.
. Install and configure any necessary NetApp software on the host.

.Related information
See link:reference_host_remediation.html[host remediation] for examples of post-migration remediation for specific host types.

// 2026 Jan 14, ONTAPDOC 3037
