---
permalink: san-migration/concept_performance_enhancements_in_clustered_data_ontap_8_3_1.html
sidebar: sidebar
keywords: performance, enhancements, ontap 8.3.1
summary: "There have been some enhancements to FLI to better manage performance and stop workload starvation from occurring. FLI enhancements in ONTAP 8.3.1 include a new throttle command and LUN import show enhancements showing throughput and QoS policy groups."
---
= Performance enhancements in ONTAP 8.3.1
:icons: font
:imagesdir: ../media/

[.lead]
There have been some enhancements to FLI to better manage performance and stop workload starvation from occurring. FLI enhancements in ONTAP 8.3.1 include a new throttle command and LUN import show enhancements showing throughput and QoS policy groups.

The LUN import throttle command is used to limit the maximum speed at which an import can run.

----
cluster::*> lun import throttle -vserver fli_72C -path /vol/flivol/72Clun1 -max-throughput-limit

{<integer>[KB|MB|GB|TB|PB]}  Maximum Throughput Limit (per sec)
----

Use the `instance` switch with `lun import show` to display extended LUN import information, including throttle and QoS information.

----
cluster::*> lun import show -instance

    Vserver Name: fli_72C
    LUN Path: /vol/flivol/72Clun1
    Foreign Disk Serial Number: D0i1E+G8Wg6m
    Import Home Node: ontaptme-fc-cluster-01
    Import Current Node: ontaptme-fc-cluster-01
    Operation In Progress: import
    Admin State: stopped
    Operational State: stopped
    Percent Complete: 0
    Blocks Imported: -
    Blocks Compared: -
    Total Blocks: 6297480
    Estimated Remaining Duration: -
    Failure Reason: -
    Maximum Throughput Limit(per sec): -
    Current Throughput (per sec): -
    QoS Policy Group: -
----

The values for the `current throughput` show the current rate of throughput of import or verify operations. Users should check this before setting a throttle value. It is empty when not running. The `QoS policy group` shows the QoS group if the LUN import throttle was used.
