---
permalink: san-migration/concept_plan_phase_procedures.html
sidebar: sidebar
keywords: 
summary: 'The FLI planning phase focuses on the tasks required to create detailed migration plans and prepare the customer environment for the actual migration. One or more test migrations are performed during this phase to verify the installation and setup of the foreign LUN import.'
---
= Plan and prepare phase procedures
:icons: font
:imagesdir: ../media/

[.lead]
The FLI planning phase focuses on the tasks required to create detailed migration plans and prepare the customer environment for the actual migration. One or more test migrations are performed during this phase to verify the installation and setup of the foreign LUN import.

The following are tasks to complete during the plan phase:

* Create a mapping of source and destination LUNs by entering the storage mapping information for each storage array in the LUN Details section of your Site Survey and Planning worksheet.
* Wire the source storage into the fabric based on the planning information.
* Configure the switch zones.
* Perform one or more test migrations to verify the installation and setup.

*Related information*

xref:reference_sample_site_survey_and_planning_worksheet.adoc[Sample Site Survey and Planning worksheet]
