---
permalink: san-migration/concept_fli_transition_post_migration_tasks.html
sidebar: sidebar
keywords: 
summary: 'The post-migration tasks for the FLI 7-mode to ONTAP workflow are similar to the other FLI workflows.'
---
= FLI transition workflow post-migration tasks
:icons: font
:imagesdir: ../media/

[.lead]
The post-migration tasks for the FLI 7-mode to ONTAP workflow are similar to the other FLI workflows.

* When ready, you can delete the LUN import relationship.
+
The LUN import relationship can be safely removed because the host is now accessing the new NetApp array for all I/O to the new ONTAP LUN, and the source 7-Mode LUN is no longer in use.

* All server remediations are performed during post-migration.
+
The third-party software is removed, NetApp software is installed and configured, and then the host is brought up accessing the LUNs on NetApp.

* Review logs for errors, check pathing, and perform any application testing to verify that your migration completed cleanly and successfully.

*Related information*

xref:reference_host_remediation.adoc[Host remediation]
