---
permalink: san-migration/configure-fc-adapter-initiator.html
sidebar: sidebar
keywords: online, migration, workflow
summary: "Initiator mode is used to connect the ports to tape drives, tape libraries, or third-party storage with Foreign LUN Import (FLI).."
---
= Configure FC adapters for initiator mode
:icons: font
:imagesdir: ../media/

[.lead]
Initiator mode is used to connect the ports to tape drives, tape libraries, or third-party storage with Foreign LUN Import (FLI). You need to convert your FC target adapter to initiator mode to use it for FLI. 

.Before you begin

* LIFs on the adapter must be removed from any port sets of which they are members.
* All LIF's from every storage virtual machine (SVM) using the physical port to be modified must be migrated or destroyed before changing the personality of the physical port from target to initiator.


.Steps

. Remove all LIFs from the adapter:
+
[source,cli]
----
network interface delete -vserver <SVM_name> -lif <lif_name>,<lif_name>
----

. Take your adapter offline:
+
[source,cli]
----
network fcp adapter modify -node <node_name> -adapter <adapter_port> -status-admin down
----
+
If the adapter does not go offline, you can also remove the cable from the appropriate adapter port on the system.

. Change the adapter from target to initiator:
+
[source,cli]
----
system hardware unified-connect modify -t initiator <adapter_port>
----

. Reboot the node hosting the adapter you changed.
. Verify that the FC ports are configured in the correct state for your configuration:
+
[source,cli]
----
system hardware unified-connect show
----

. Bring the adapter back online:
+
[source,cli]
----
node run -node _node_name_ storage enable adapter <adapter_port>
----

.What's next

Zone the target ports of the foreign array with initiator ports of of your ONTAP storage.