---
permalink: san-migration/create-lun-import-relationship-offline.adoc.html
sidebar: sidebar
keywords: configure, migration, jobs
summary: "Before you can migrate a LUN from a foreign array to ONTAP storage, you must create a LUN import relationship.  A LUN import relationship is a persistent pairing between the source and destination storage for the purpose of data import."
---
= Create the LUN import relationship for an FLI offline migration
:icons: font
:imagesdir: ../media/

[.lead]
Before you can migrate a LUN from a foreign array to ONTAP storage, you must create a LUN import relationship.  A LUN import relationship is a persistent pairing between the source and destination storage for the purpose of data import.  The source and destination endpoints are LUNs.

Creating the LUN import relationship for FLI offline migrations includes identifying the source array LUNs as foreign in ONTAP, creating and configuring the destination volume to contain the foreign LUNs, creating destination target LUNs and finally establishing the import relationship.

.Before you begin

You should have completed the steps to link:prepare-foreign-lun-offline.html[prepare your foreign LUNs for FLI offline migration].

== Step 1: Identify the source array LUNs as foreign in ONTAP
You’ll need to identify the source array LUNs as foreign LUNs in ONTAP before you begin your FLI offline migration.

.Steps

. Use the serial number to mark the source LUN as foreign in ONTAP:
+
----
storage disk set-foreign-lun -serial-number <lun_serial_number> -is-foreign true
----
+
----

DataMig-cmode::*> storage disk set-foreign-lun { -serial-number 83017542001E }
                   -is-foreign true
DataMig-cmode::*> storage disk set-foreign-lun { -serial-number 83017542000E }
                   -is-foreign true
DataMig-cmode::*> storage disk set-foreign-lun { -serial-number 83017542000F }
                   -is-foreign true
----

. Verify the source LUN is marked as foreign.
+
----
DataMig-cmode::*> storage disk show -array-name HITACHI_DF600F_1 -fields disk, serial-number, container-type, owner,import-in-progress, is-foreign
disk     owner is-foreign container-type import-in-progress serial-number
-------- ----- ---------- -------------- ------------------ -------------
HIT-1.2  -     true       foreign        false              83017542001E
HIT-1.3  -     true       foreign        false              83017542000E
HIT-1.4  -     true       foreign        false              83017542000F
3 entries were displayed.
----

== Step2: Create and configure a destination volume

Before you create the LUN import relationship for an FLI offline migration, you must create a volume on your ONTAP storage system to contain the LUNs you will import from your foreign array.

.Steps

. Create a destination volume.
+
----
DataMig-cmode::*> vol create -vserver datamig winvol aggr1 -size 100g
[Job 5606] Job succeeded: Successful
----

. Disable the default Snapshot policy on each volume. If default Snapshot copies exist prior to FLI migration, the volume needs additional space to store changed data.
+
----
DataMig-cmode::> volume modify -vserver datamig -volume winvol -snapshot-policy none

Warning: You are changing the Snapshot policy on volume winvol to none.  Any Snapshot copies on this volume from the previous policy will not be deleted by
         this new Snapshot policy.
Do you want to continue? {y|n}: y
Volume modify successful on volume winvol of Vserver datamig.
----

. Set `fraction_reserveoption` for each volume to `0` and set the Snapshot policy to `none`.
+
----
DataMig-cmode::> vol modify -vserver datamig -volume * -fractional-reserve 0 –snapshot-policy none
Volume modify successful on volume winvol of Vserver datamig.
----

. Verify your volume settings.
+
----
DataMig-cmode::> vol show -vserver datamig -volume * -fields fractional-reserve,snapshot-policy
vservervolumesnapshot-policyfractional-reserve
-----------------------------------------------
datamig datamig_rootnone0%
datamigwinvolnone0%
Volume modify successful on volume winvol of Vserver datamig.
----

. Delete any existing Snapshot copies.
+
----
DataMig-cmode::> set advanced; snap delete –vserver datamig –vol winvol –snapshot * -force true
1 entry was acted on.
----
+
[NOTE]
====
FLI migration modifies every block of the target LUN. If default or other Snapshot copies exist on a volume prior to FLI migration, the volume gets filled up. Changing the policy and removing any existing Snapshot copies before FLI migration are required. Snapshot policy can be set again post-migration.
====

== Step 3: Create the destination LUNs and LUN import relationship

For FLI offline migration, the destination LUNs on your ONTAP storage system, must be created and mapped to an igroup; then they must be offlined before creating the LUN import relationship.

.Steps

. Use the foreign LUNs to create destination LUNs.
+
----
DataMig-cmode::*> lun create -vserver datamig -path /vol/winvol/bootlun -ostype windows_2008 -foreign-disk 83017542001E

Created a LUN of size 40g (42949672960)

Created a LUN of size 20g (21474836480)
DataMig-cmode::*> lun create -vserver datamig -path /vol/linuxvol/lvmlun1 -ostype linux -foreign-disk 830175420011

Created a LUN of size 2g (2147483648)
DataMig-cmode::*> lun create -vserver datamig -path /vol/esxvol/bootlun -ostype vmware -foreign-disk 830175420014

Created a LUN of size 20g (21474836480)
----
+
[NOTE]
====
The LUN create command detects the size and alignment based on partition offset and creates the LUN accordingly with foreign-disk option. For a review, see the NetApp Knowledgebase article *What is an unaligned I/O?* Also note that some I/O will always appear be partial writes and will therefore look misaligned. Examples of this would be database logs.
====


. Verify the size and source LUN of the newly created LUNs.
+
----
DataMig-cmode::*> lun show -vserver datamig
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
datamig   /vol/esxvol/bootlun             online  unmapped vmware       20GB
datamig   /vol/esxvol/linuxrdmvlun        online  unmapped linux         2GB
datamig   /vol/esxvol/solrdmplun          online  unmapped solaris       2GB
datamig   /vol/winvol/gdrive              online  unmapped windows_2008  3GB
4 entries were displayed.
----

. Create a host igroup of protocol FCP and add host initiators. Find initiator WWPNs from storage groups section of your Site Survey planning worksheet.
+
----
DataMig-cmode::*> lun igroup create -ostype windows -protocol fcp -vserver datamig -igroup dm-rx200s6-21 -initiator 21:00:00:24:ff:30:14:c4,21:00:00:24:ff:30:14:c5

DataMig-cmode::*> lun igroup create -ostype linux -protocol fcp -vserver datamig  -igroup dm-rx200s6-22 -initiator 21:00:00:24:ff:30:04:85,21:00:00:24:ff:30:04:84

DataMig-cmode::*> lun igroup create -ostype vmware -protocol fcp -vserver datamig -igroup dm-rx200s6-20 -initiator 21:00:00:24:ff:30:03:ea,21:00:00:24:ff:30:03:eb
----
+
[NOTE]
====
Use the same LUN ID as source. Refer to source LUNS section of your Site Survey planning worksheet.
====

. Map the destination LUNs to an igroup.
+
----
DataMig-cmode::*> lun map -vserver datamig -path /vol/winvol/bootlun -igroup dm-rx200s6-21 -lun-id 0
DataMig-cmode::*> lun map -vserver datamig -path /vol/linuxvol/bootlun -igroup dm-rx200s6-22 -lun-id 0
DataMig-cmode::*> lun map -vserver datamig -path /vol/esxvol/bootlun -igroup dm-rx200s6-20 -lun-id 0
----

. Offline the destination LUNs.
+
----
DataMig-cmode::*> lun offline -vserver datamig -path /vol/esxvol/bootlun
DataMig-cmode::*> lun offline -vserver datamig -path /vol/esxvol/linuxrdmvlun
DataMig-cmode::*> lun offline -vserver datamig -path /vol/esxvol/solrdmplun
----

. Create the LUN import relationship between the destination and source LUNs.
+
----
DataMig-cmode::*> lun import create -vserver datamig -path /vol/winvol/bootlun -foreign-disk 83017542001E
DataMig-cmode::*> lun import create -vserver datamig -path /vol/linuxvol/ext3lun -foreign-disk 830175420013
DataMig-cmode::*> lun import create -vserver datamig -path /vol/esxvol/linuxrdmvlun -foreign-disk 830175420018
DataMig-cmode::*> lun import create -vserver datamig -path /vol/esxvol/solrdmplun -foreign-disk 830175420019
----

. Verify the LUN import relationship is created.
+
----
DataMig-cmode::*> lun import show -vserver datamig
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
datamig 83017542000E   /vol/winvol/fdrive  import    stopped
                                                           stopped            0
datamig 83017542000F   /vol/winvol/gdrive  import    stopped
                                                           stopped            0
datamig 830175420010   /vol/linuxvol/bootlun
                                           import    stopped
                                                           stopped            0
3 entries were displayed.
----

.Related information

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/What_is_an_unaligned_I%2F%2FO%3F[What is an unaligned I/O?]

// 2025 June 23, ONTAPDOC-3057