---
permalink: san-migration/prepare-foreign-lun-offline.html
sidebar: sidebar
keywords: present, source luns, ontap storage, fli
summary: "In the FLI offline migration process, you must present the foreign source LUN to the ONTAP storage; then you must discover the foreign source LUN on the ONTAP storage."
---
= Prepare the foreign LUN for FLI offline migration
:icons: font
:imagesdir: ../media/

[.lead]
In the FLI offline migration process, you must take manual steps from your foreign array to present the foreign source LUN to the ONTAP storage; then you must take additional manual steps to discover the foreign source LUN on the ONTAP storage.

== Presenting source LUNs to ONTAP storage during FLI

As part of the offline FLI process, you must present your source LUNs to your ONTAP storage.

.Steps

. Log in to the source array.
. Add the NetApp initiators to the host group created during the plan phase.
. Select the host LUNs that need to be migrated from available logical LUNs. Use LUN names for each host mentioned in the source LUNs section of your Site Survey and Planning worksheet.


== Discover foreign source LUNs in ONTAP for an offline FLI migration

After you have presented your foreign array source LUN to your ONTAP destination storage system, you must verify your source LUNs on your destination storage.

.Steps

. Verify the source LUNs and mapping from the source storage to the destination storage.
. Log in to the ONTAP storage system through SSH using admin user.
. Change the mode to advanced: `set -privilege advanced`
. Enter `y` when asked if you want to continue.
. Discover the source array on ONTAP. Wait for a few minutes and retry to detect the source array. `storage array show`
+
----
DataMig-cmode::*> storage array show
Prefix                         Name   Vendor            Model Options
-------- ---------------------------- -------- ---------------- ----------
HIT-1                HITACHI_DF600F_1  HITACHI           DF600F
----
+
[NOTE]
====
When the storage array is discovered for the first time, ONTAP might not show the array by discovering automatically. Use the following instructions to reset the switch port where ONTAP initiator ports are connected.
====

. Verify the source array is discovered through all the initiator ports.
+
----
DataMig-cmode::*> storage array config show -array-name HITACHI_DF600F_1
             LUN   LUN
Node         Group Count     Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- -----------------------
DataMig-cmode-01 0     1    HITACHI_DF600F_1     50060e801046b960        0a
                                                 50060e801046b964        0b
                                                 50060e801046b968        0a
                                                 50060e801046b96c        0b
DataMig-cmode-02 0     1    HITACHI_DF600F_1     50060e801046b960        0a
                                                 50060e801046b964        0b
                                                 50060e801046b968        0a
                                                 50060e801046b96c        0b
----

. List the source LUNs mapped from Hitachi storage. Verify the disk properties and paths.
+
You should see the number of paths expected based on your cabling (at least two paths for each source controller). You should also check the event log after masking the array LUNs.
+
----
DataMig-cmode::*> storage disk show -array-name HITACHI_DF600F_1 -fields disk, serial-number, container-type, owner, path-lun-in-use-count, import-in-progress, is-foreign
disk     owner is-foreign container-type import-in-progress path-lun-in-use-count serial-number
-------- ----- ---------- -------------- ------------------ --------------------- -------------
HIT-1.2  -     false      unassigned     false        0,0,0,0,0,0,0,0       83017542001E
HIT-1.3  -     false      unassigned     false        0,0,0,0,0,0,0,0       83017542000E
HIT-1.14 -     false      unassigned     false        0,0,0,0,0,0,0,0       830175420019
3 entries were displayed.

DataMig-cmode::*>
----

// 23 June 2025, ONTAPDOC-3057