---
permalink: san-migration/prepare-foreign-lun-offline.html
sidebar: sidebar
keywords: present, source luns, ontap storage, fli
summary: "In the FLI offline migration process, you must present the foreign source LUN to the ONTAP storage; then you must discover the foreign source LUN on the ONTAP storage."
---
= Prepare foreign storage array LUNs for an ONTAP FLI offline migration
:icons: font
:imagesdir: ../media/

[.lead]
In a Foreign LUN Import (FLI) offline migration, you must take manual steps from your foreign storage array to present the foreign source LUN to your ONTAP storage system; then you must take steps from your ONTAP storage system to discover the foreign LUN.

== Step 1: Present foreign array source LUNs to ONTAP storage

Before you can begin importing data from a foreign storage array LUN using an FLI offline migration, you must present the source LUNs on your foreign storage array to your ONTAP storage system.

.Steps

. Log in to the source array.
. Add the NetApp initiators to the host group created during the plan phase.
. Select the host LUNs that need to be migrated from available logical LUNs.
+
Use LUN names for each host mentioned in the source LUNs section of your link:reference_site_survey_and_planning_worksheet_source_luns_tab.html[Site Survey and Planning worksheet].


== Step 2: Discover foreign array source LUNs in ONTAP

After you have presented your foreign array source LUNs to your ONTAP storage system, the LUNs must be discovered in ONTAP before you can create the LUN import relationship.

.Steps

. Verify the source LUNs and mapping from the source storage to the destination storage.
. Log in to the ONTAP storage system through SSH using admin user.
. Change the mode to advanced. 
+
[source,cli]
----
set -privilege advanced
----
. Enter `y` when asked if you want to continue.
. Discover the source array on ONTAP. Wait for a few minutes and retry to detect the source array. 
+
[source,cli]
----
storage array show
----
+
The following example shows the discovery of a Hitachi DF600F array.
+
----
DataMig-ontap::*> storage array show
Prefix                         Name   Vendor            Model Options
-------- ---------------------------- -------- ---------------- ----------
HIT-1                HITACHI_DF600F_1  HITACHI           DF600F
----
+
[NOTE]
====
When the storage array is discovered for the first time, ONTAP might not show the array by discovering automatically. Use the following instructions to reset the switch port where ONTAP initiator ports are connected.
====

. Verify the source array is discovered through all the initiator ports.
+
[source,cli]
----
storage array config show -array-name <array_name>
----
+
The following example shows the Hitachi DF600F array discovered through all the initiator ports.
+
----
DataMig-ontap::*> storage array config show -array-name HITACHI_DF600F_1
             LUN   LUN
Node         Group Count     Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- -----------------------
DataMig-ontap-01 0     1    HITACHI_DF600F_1     50060e801046b960        0a
                                                 50060e801046b964        0b
                                                 50060e801046b968        0a
                                                 50060e801046b96c        0b
DataMig-ontap-02 0     1    HITACHI_DF600F_1     50060e801046b960        0a
                                                 50060e801046b964        0b
                                                 50060e801046b968        0a
                                                 50060e801046b96c        0b
----

.What's next?
link:create-lun-import-relationship-offline.adoc.html[Create the LUN import relationship].

// 2025 June 23, ONTAPDOC-3057