---
permalink: san-migration/reference_clearing_scsi_3_persistent_reservations.html
sidebar: sidebar
keywords: 
summary: 'If you have a Windows cluster, you need to remove SCSI-3 reservations for the quorum disk, even if all clustered hosts are offline.'
---
= Clearing SCSI-3 persistent reservations
:icons: font
:imagesdir: ../media/

[.lead]
If you have a Windows cluster, you need to remove SCSI-3 reservations for the quorum disk, even if all clustered hosts are offline.

 If you attempt to label the source LUN as a foreign disk, the following error message will appear:

Error: command failed: The specified foreign disk has SCSI persistent reservations. Disk serial number: "6006016021402700787BAC217B44E411". Clear the reservation using the "storage disk remove-reservation" command before creating the import relationship.

You can remove SCSI-3 reservations for the quorum disk on the NetApp controller using the storage disk remove-reservation command:

----
storage disk remove-reservation –disk disk_name
----

Here is a snippet showing this error and the remediation for it:

----
cluster-4b::*> lun offline -vserver fli_cluster -path /vol/fli_volume/cluster_CVS
cluster-4b::*> lun import create -vserver fli_cluster -path /vol/fli_volume/cluster_CVS -foreign-disk 6006016021402700787BAC217B44E411
Error: command failed: The specified foreign disk is not marked as foreign. Disk serial number: "6006016021402700787BAC217B44E411".

cluster-4b::*> sto disk show -disk DGC-1.6 -fields serial-number,is-foreign
 (storage disk show)
disk is-foreign serial-number
------- ---------- --------------------------------
DGC-1.6 true 6006016021402700787BAC217B44E411

cluster-4b::*> lun import create -vserver fli_cluster -path /vol/fli_volume/cluster_CVS -foreign-disk 6006016021402700787BAC217B44E411

Error: command failed: The specified foreign disk has SCSI persistent reservations. Disk serial number: "6006016021402700787BAC217B44E411". Clear the reservation using the "storage disk remove-reservation" command before creating the import relationship.

cluster-4b::*> storage disk remove-reservation -disk DGC-1.6
cluster-4b::*> lun import create -vserver fli_cluster -path /vol/fli_volume/cluster_CVS -foreign-disk 6006016021402700787BAC217B44E411
cluster-4b::*> lun online -vserver fli_cluster -path /vol/fli_volume/cluster_CVS
cluster-4b::*> lun import show

vserver foreign-disk path operation admin operational percent in progress state state complete
 -------------------------------------------------------------------------------
fli_cluster 6006016021402700787BAC217B44E411 /vol/fli_volume/cluster_CVS import stopped stopped 0

cluster-4b::*> lun import start -vserver fli_cluster -path /vol/fli_volume/cluster_CVS
cluster-4b::*> lun import show

vserver foreign-disk path operation admin operational percent in progress state state complete
-------------------------------------------------------------------------------
fli_cluster 6006016021402700787BAC217B44E411 /vol/fli_volume/cluster_CVS import started in_progress 7
----
