---
permalink: san-migration/reference_site_survey_and_planning_worksheet_questionnaire_tab.html
sidebar: sidebar
keywords: site, survey and planning worksheet, questionnaire tab
summary: "As part of your Site Survey and Planning worksheet, you should have a tab containing migration project information from your initial migration questionnaire."
---
= Site Survey and Planning worksheet Questionnaire tab
:icons: font
:imagesdir: ../media/

[.lead]
As part of your Site Survey and Planning worksheet, you should have a tab containing migration project information from your initial migration questionnaire.

The following is an example of how to set up your Questionnaire tab.
[options="header"]
|===
3+a| Migration Project Information

a|
Project Type
a|
☐ Data Migration

☐ Other

a|

a|
Data Migration Objectives
a|
[Objectives]
a|

a|
Source Devices
a|
Storage: [Storage Type]

No. of Devices: [No. of arrays]

Thin-provisioned: ☐ Yes ☐ No

a|
Enumerate all devices
a|
Client Devices
a|
Operating System: [OS Version]

SAN boot: ☐ Yes ☐ No

MPIO: [MPIO Version]

HBAs: [HBA Vendor, Model, Firmware]

a|

a|
Fabric Switches
a|
Vendor:

Model:

Firmware:

No. of Ports:

a|

a|
Current Protocols
a|
☐ FCP

☐ iSCSI

a|

a|
Volume Manager
a|
Vendor:

Product:

Version:

a|

a|
Destination Devices (Storage)
a|
Storage: [Storage]

No. [Number]

Thin-provisioned: ☐ Yes ☐ No

a|
For this service, NetApp filers only
a|
Amount of Datato be Migrated (in TB)

a|
[Amount of Data]
a|
Summary and detail (each source device)
a|
Number of LUNs
a|
[Number of LUNs]
a|
Summary and detail (each source device)
a|
Data Reorganization
a|
☐ Yes☐ No
a|
Does the customer desire to move volumes/directories/folders/files into different data structures as part of the migration?
a|
Outage Expectations
a|
Outage Window

☐ Pre-defined ☐ Flexible

Standard Maintenance window polices : [Info]

a|
Number and durations of outages that can be utilized. Please list maintenance windows, if any.
a|
Desired Time frame for Completion
a|
[Desired Time frame for Completion][Time Sensitivities]

a|

a|
Other Relevant Information
a|
[Other Relevant Information]

a|

a|
Customer Organization Name and Location (City and State)
a|

a|

|===
