---
permalink: san-migration/reference_host_remediation.html
sidebar: sidebar
keywords: host remediation
summary: "Depending on the type of migration, host remediation may take place inline to the migration (Foreign LUN Import online, and 7-Mode to ONTAP) or might it occur after the migration is complete (Foreign LUN Import offline)."
---
= Host remediation
:icons: font
:imagesdir: ../media/

[.lead]
Depending on the type of migration, host remediation may take place inline to the migration (Foreign LUN Import online, and 7-Mode to ONTAP) or might it occur after the migration is complete (Foreign LUN Import offline).

Use the for remediation steps for different host OSs. Consult your gap analysis, put together during the planning and analysis phases, and appropriate NetApp and vendor documentation for steps specific to your migration.

[NOTE]
====
FLI uses the same remediation procedures that would be used with the 7MTT. Therefore, it makes sense to leverage the same remediation document rather than document those procedures multiple times in different places.
====

[NOTE]
====
For CAW remediation, use the ESXi CAW/ATS remediation process.
====

*Related information*

https://docs.netapp.com/us-en/ontap-7mode-transition/san-host/index.html[SAN host transition and remediation]
