---
permalink: san-migration/remove-lun-import-relationship.html
sidebar: sidebar
keywords: fli offline, verify, migration, results
summary: "A verify job is optional, but recommended. It is a block-by-block comparison of the source and destination LUNs. Verify jobs take almost the same or slightly more time than migration time."
---
= Remove the LUN import relationship after an FLI offline migration
:icons: font
:imagesdir: ../media/

[.lead]

After the FLI offline migration is completed, the LUN import relationship can be safely removed.  The host is now accessing the new NetApp array for all I/O to the new ONTAP LUN and the source LUN is no longer in use so the import relationship is no longer needed.

.Steps

. Delete the import relationship to remove the migration job.
+
----
DataMig-cmode::*> lun import delete -vserver datamig -path /vol/winvol/bootlun

DataMig-cmode::*> lun import delete -vserver datamig -path /vol/winvol/fdrive

DataMig-cmode::*> lun import delete -vserver datamig -path /vol/winvol/gdrive
----

. Verify import jobs are deleted.
+
----
DataMig-cmode::*> lun import show -vserver datamig
There are no entries matching your query.
----

. Mark the foreign LUN attribute to `false`.
+
----

DataMig-cmode::*> storage disk modify { -serial-number 83017542001E }
-is-foreign false

DataMig-cmode::*> storage disk modify { -serial-number 83017542000E }
-is-foreign false

DataMig-cmode::*> storage disk modify { -serial-number 83017542000F }
-is-foreign false
----

. Verify the foreign LUNs are marked as `false` after import.
+
----
DataMig-cmode::*> storage disk show -array-name HITACHI_DF600F_1 -fields disk, serial-number, container-type, owner,import-in-progress, is-foreign
disk     owner is-foreign container-type import-in-progress serial-number
-------- ----- ---------- -------------- ------------------ -------------
HIT-1.2  -     false      unassigned     false              83017542001E
HIT-1.3  -     false      unassigned     false              83017542000E
HIT-1.4  -     false      unassigned     false              83017542000F
3 entries were displayed.
----

. Bring the destination LUNs online using the lun online command.
+
----
DataMig-cmode::*> lun online -vserver datamig -path /vol/winvol/bootlun

DataMig-cmode::*> lun online -vserver datamig -path /vol/winvol/fdrive

DataMig-cmode::*> lun online -vserver datamig -path /vol/winvol/gdrive
----

. Verify the LUNs are online.
+
----
DataMig-cmode::*> lun show -vserver datamig
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
datamig   /vol/esxvol/bootlun             online  mapped   vmware       20GB
datamig   /vol/esxvol/linuxrdmvlun        online  mapped   linux         2GB
datamig   /vol/esxvol/solrdmplun          online  mapped   solaris       2GB
3 entries were displayed.
----
+
[NOTE]
====
Import logs are stored in cluster event log file.
====
+
----
  DataMig-cmode::*> event log  show –event fli*
  7/7/2014 18:37:21   DataMig-cmode-01 INFORMATIONAL fli.lun.verify.complete: Import verify of foreign LUN 83017542001E of size 42949672960 bytes from array model DF600F belonging to vendor HITACHI  with NetApp LUN QvChd+EUXoiS is successfully completed.
  7/7/2014 18:37:15   DataMig-cmode-01 INFORMATIONAL fli.lun.verify.complete: Import verify of foreign LUN 830175420015 of size 42949672960 bytes from array model DF600F belonging to vendor HITACHI  with NetApp LUN QvChd+EUXoiX is successfully completed.
  7/7/2014 18:02:21   DataMig-cmode-01 INFORMATIONAL fli.lun.import.complete: Import of foreign LUN 83017542000F of size 3221225472 bytes from array model DF600F belonging to vendor HITACHI  is successfully completed. Destination NetApp LUN is QvChd+EUXoiU.
----


// 2025 June 23, ONTAPDOC-3057