---
permalink: san-migration/task_fli_transition_verifying_fli_7_mode_to_ontap_migration.html
sidebar: sidebar
keywords: verify, fli 7-mode, ontap, migration, results
summary: "You have the option to verify that LUNs have been properly migrated from FLI 7-Mode to ONTAP."
---
= Verifying FLI 7-Mode to ONTAP migration results
:icons: font
:imagesdir: ../media/

[.lead]
You have the option to verify that LUNs have been properly migrated from FLI 7-Mode to ONTAP.

Start the verify job to compare source and destination LUNs. Monitor the verify progress. The LUNs being verified need to be offline for the duration of the verification session. The verification session can potentially be lengthy because it is a block-for-block comparison between source and destination LUNs. It should take approximately the same amount of time as the migration. Verification is not required, but we encourage you to verify a subset of the LUNs imported/migrated to feel comfortable about the import process.

[NOTE]
====
The LUN import verify must be explicitly stopped before bringing the LUN back online. Otherwise, the LUN online fails. This behavior will be changed in an upcoming release of ONTAP.
====

.Steps
. Offline the LUNs to be verified.
+
----
cluster::*> lun offline -vserver fli_72C -path /vol/flivol/72Clun1
Warning: This command will take LUN "/vol/flivol/72Clun1" in Vserver "fli_72C" offline.
Do you want to continue? {y|n}: y
----

. Start LUN verify.
+
----
lun import verify start -vserver fli_72C -path /vol/flivol/72Clun1
----

. Display LUN verify status.
+
----
ontaptme-fc-cluster::*> lun import show -vserver fli_72C -path /vol/flivol/72Clun1
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
fli_72C D0i1E+G8Wg6m   /vol/flivol/72Clun1 verify    started
                                                                        9
----
+
[NOTE]
====
The LUN import verify must be explicitly stopped before bringing the LUN back online. Otherwise, the LUN online fails. See the following CLI output.
====

. Stop LUN verification. This step needs to be performed manually even if the status shows that verify is complete.
+
----
lun import verify stop -vserver fli_72C -path /vol/flivol/72Clun1
----

. Online the LUN upon completion of verification.
+
----
lun online -vserver fli_72C -path /vol/flivol/72Clun1
----
