---
permalink: san-migration/task_fli_offline_verifying_migration_results.html
sidebar: sidebar
keywords: fli offline, verify, migration, results
summary: "A verify job is optional, but recommended. It is a block-by-block comparison of the source and destination LUNs. Verify jobs take almost the same or slightly more time than migration time."
---
= Verify FLI offline migration results
:icons: font
:imagesdir: ../media/

[.lead]
After your LUN is migrated from the foreign array to your ONTAP storage system, FLI can perform a block-by-block comparison of the source and destination LUNs to verify that the migration is complete and accurate.  A migration verification takes approximately the same amount of time as (or slightly more than) the migration.

A migration verification is not required but is highly recommended.

.Steps
. Start the LUN migration verification.
+
----
DataMig-cmode::*> lun import verify start -vserver datamig -path /vol/winvol/bootlun

DataMig-cmode::*> lun import verify start -vserver datamig -path /vol/winvol/fdrive

DataMig-cmode::*> lun import verify start -vserver datamig -path /vol/winvol/gdrive
----

. Monitor the verification status.
+
----
DataMig-cmode::*> lun import show -vserver datamig -fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, , estimated-remaining-duration
vserver foreign-disk path               admin-state operational-state percent-complete imported-blocks total-blocks estimated-remaining-duration
------- ------------ ------------------ ----------- ----------------- ---------------- --------------- ------------ ----------------------------
datamig 83017542000E /vol/winvol/fdrive started     in_progress       57               -               4194304      00:01:19
datamig 83017542000F /vol/winvol/gdrive started     in_progress       40               -               6291456      00:02:44
datamig 830175420010 /vol/linuxvol/bootlun
                                        started     in_progress       8                -               41943040     00:20:29
3 entries were displayed.
----
+
You can execute the same command to track the progress of the verification.  The *operatioanl-state* displays a status of *completed* when the verification job is completed successfully.


. Stop the LUN verification.
+
----
DataMig-cmode::*> lun import verify stop -vserver datamig -path /vol/esxvol/winrdmplun
----
+
The LUN import verification must be explicitly stopped before bringing the LUN back online. Otherwise, the `lun online` command fails. This step must be performed manually even if the status shows that the verification is completed.

// 23 June 2025, ONTAPDOC-3057
