---
permalink: san-migration/task_fli_transition_performing_a_disruptive_cutover.html
sidebar: sidebar
keywords: perform, disruptive, cutover, fli 7-mode, ontap
summary: "This example gives you the general steps for performing a disruptive cutover for the FLI transition process."
---
= Performing a disruptive cutover of FLI 7-Mode to ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
This example gives you the general steps for performing a disruptive cutover for the FLI transition process.

For a host remediation walkthrough of Windows, Linux, and ESXi hosts, see related topics in this guide as well as the host operating system and host-attach kit documentation.

.Steps
. On the 7-Mode system, display the igroup to which the source LUN is mapped.
+
----
stme-7ma> igroup show
    FLI_on_fcp (FCP) (ostype: windows):
        10:00:00:00:c9:e6:e2:79 (logged in on: 0c, vtic)
        50:0a:09:81:00:96:43:70 (logged in on: 0c, vtic)
        50:0a:09:81:00:96:3c:f0 (logged in on: 0c, vtic)
----
+
[NOTE]
====
The disruption begins immediately after the unmap command is executed. Generally, the disruption window can be measured in minutes. It is literally the length of time it takes to move the host to the new NetApp target and scan for LUNs.
====

. If the LUNs being imported are for ESXi hosts, review and follow the instructions in the _ESXi CAW/ATS remediation_ topic.
. Use the unmap command to move the LUN from its hosts. (The disruption window begins here.)
+
----
stme-7ma> igroup remove -f FLI_on_fcp 10:00:00:00:c9:e6:e2:79
----

. Verify that the host initiators are no longer present.
+
----
stme-7ma> igroup show
    FLI_on_fcp (FCP) (ostype: windows):
        50:0a:09:81:00:96:43:70 (logged in on: 0c, vtic)
        50:0a:09:81:00:96:3c:f0 (logged in on: 0c, vtic)
----

. On the ONTAP cluster, bring the destination LUN online and verify that it's mapped.
+
----
cluster::*> lun online -vserver fli_72C -path /vol/flivol/72Clun1

cluster::*> lun show -path /vol/flivol/72Clun1
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
fli_72C   /vol/flivol/72Clun1             online  mapped   windows_2008
                                                                      3.00GB
----

. Rescan disks on the host; find the LUN on the ONTAP target.
+
[NOTE]
====
The disruption window ends here.
====
+
The LUNs are online and mapped, and hosts are now mounting the new ONTAP hosted LUN. Reads are passed through the ONTAP array to the source LUN, and writes are written to both the new ONTAP hosted LUN and also the original source LUN. Both source and destination LUNs will remain in sync until the migration is complete and the LUN relationship has been broken.
