---
permalink: san-migration/task_fli_online_verifying_migration_results.html
sidebar: sidebar
keywords: fli online, verify, migration, results
summary: "A verify job is optional, but recommended. It is a block-by-block comparison of the source and destination LUNs. Verify jobs take almost the same or slightly more time than migration time."
---
= Verify FLI online migration results
:icons: font
:imagesdir: ../media/

[.lead]
After your LUN is migrated from the foreign array to the ONTAP array, FLI can perform a block-by-block comparison of the source and destination LUNs to verify that the migration is complete and accurate.  A migration verification takes approximately the same amount of time as (or slightly more than) the migration.

A migration verification is not required, but is highly recommended.

.About this task

* Beginning with ONTAP 9.17.1, data migration of foreign LUNs using FLI offline migration is supported with link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html[ASA r2 systems^]. ASA r2 systems vary from other ONTAP systems (ASA, AFF, and FAS) in the implementation of its storage layer.  In ASA r2 systems, volumes are automatically created when a storage unit (LUN or namespace) is created. Each volume contains only one storage unit. Therefore, for ASA r2 systems, you do not need to include the volume name in the  `-path` option when creating the LUN; you include the storage unit path instead.  

* A migration verification is disruptive.  The LUNs being verified need to be offline for the duration of the verification. 

.Steps

. Offline the LUNs to be verified. 
+
----
cluster::*> lun offline -vserver fli_72C -path /vol/flivol/72Clun1
Warning: This command will take LUN "/vol/flivol/72Clun1" in Vserver "fli_72C" offline.
Do you want to continue? {y|n}: y
----
+
The disruption window begins here.

. Start the LUN migration verification.
+
----
lun import verify start -vserver fli_72C -path /vol/flivol/72Clun1
----

. Monitor the verification status.
+
----
ontaptme-fc-cluster::*> lun import show -vserver fli_72C -path /vol/flivol/72Clun1
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
fli_72C D0i1E+G8Wg6m   /vol/flivol/72Clun1 verify    started
                                                                        9
----

. Stop the LUN verification. 
+
----
lun import verify stop -vserver fli_72C -path /vol/flivol/72Clun1
----
+
The LUN import verify must be explicitly stopped before bringing the LUN back online. Otherwise, the LUN online fails.  This step must be performed manually even if the status shows that the verification is complete.

. Online the LUN . 
+
----
lun online -vserver fli_72C -path /vol/flivol/72Clun1
----
+
The disruption window ends here.

// 2025 June 23, ONTAPDOC-3058
