---
permalink: san-migration/task_fli_transition_preparing_source_and_destination_arrays.html
sidebar: sidebar
keywords: 
summary: 'To prepare for the FLI 7-mode to ONTAP migration, verify the host and source LUN paths and other details.'
---
= Preparing source and destination arrays for migration
:icons: font
:imagesdir: ../media/

[.lead]
To prepare for the FLI 7-mode to ONTAP migration, verify the host and source LUN paths and other details.

. In ONTAP, change to `advanced` privilege level.
+
----
cluster::> set adv

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by NetApp personnel.
Do you want to continue? {y|n}: y

cluster::*>
----

. Verify that the source array can be seen on the destination controller.
+
----
cluster::*> storage array show
Prefix                         Name   Vendor            Model Options
-------- ---------------------------- -------- ---------------- ----------
NET-1                    NETAPP_LUN_1   NETAPP              LUN

cluster::*> storage array config show -array-name NETAPP_LUN_1
             LUN   LUN
Node         Group Count                   Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- ----------------------- ---------
ontaptme-fc-cluster-01
                 1     2                 NETAPP_LUN_1        500a0981880b813d        0d
                                                             500a0981980b813d        0d
ontaptme-fc-cluster-02
                 1     2                 NETAPP_LUN_1        500a0981880b813d        0d
                                                             500a0981980b813d        0d
4 entries were displayed.

Warning: Configuration errors were detected.  Use 'storage errors show' for detailed information.
----

. View details on any storage errors listed. Some errors might require action before proceeding. However, the errors shown in the following example, "`This device is an ONTAP(R) LUN.`" can be safely ignored.

[NOTE]
====
The error message “This device is an ONTAP\(R\) LUN.” is caused because FLI relies on FlexArray technology which doesn’t support virtualizing ONTAP or ONTAP targets. FLI is able to import the LUNs, however, FlexArray doesn’t support virtualizing them.
====
+
Wombat: insert messageblock content here.

. Display source LUN details.
. Verify the source array is discovered through all the initiator ports.
. List the LUNs mapped from the 7-Mode storage. Verify the disk properties and paths.
. Verify the source LUN is marked as foreign.
. Serial numbers are used in FLI LUN import commands. List all foreign LUNs and their serial numbers.
. Create the target LUN. The LUN create command detects the size and alignment based on partition offset and creates the LUN accordingly with the foreign-disk argument
. Verify volume.
. Create the target LUN.
. Verify new LUN.
. Create an igroup of protocol FCP with host initiators.
. Map the test LUN to the test igroup.
. Offline the test LUN.
. Create import relationship between new LUN and foreign LUN.
