---
permalink: san-migration/task_importing_non_fc_luns.html
sidebar: sidebar
keywords: import, non-fc luns
summary: "Because Foreign LUN Import (FLI) leverages FlexArray technology to mount foreign LUNs, it can only connect to source arrays using FCP. Only FC LUNs are supported by FLI. However, there is a workaround that allows you to import iSCSI LUNs. Because you will be importing the iSCSI LUNs as FC LUNs, unlike other FLI online 7-Mode to ONTAP workflows, the disruption window would span this entire workflow:"
---
= Importing non-FC LUNs
:icons: font
:imagesdir: ../media/

[.lead]
Because Foreign LUN Import (FLI) leverages FlexArray technology to mount foreign LUNs, it can only connect to source arrays using FCP. Only FC LUNs are supported by FLI. However, there is a workaround that allows you to import iSCSI LUNs. Because you will be importing the iSCSI LUNs as FC LUNs, unlike other FLI online 7-Mode to ONTAP workflows, the disruption window would span this entire workflow:

Because you will be importing the iSCSI LUNs as FC LUNs, unlike other FLI online 7-Mode to ONTAP workflows, the disruption window would span this entire workflow.

.Steps
. On the source array, you will need to unmap the desired iSCSI LUN from its iSCSI igroup.
. On the source array, map the LUN to a FC igroup, making sure that the destination array WWPNs have been added to the igroup.
. Import the LUN.
. After the LUN has been imported, you can create a new iSCSI igroup and add the hosts to the igroup.
. On the hosts, rescan for LUNs.
+
Refer to the Interoperability Matrix Tool (IMT) on the NetApp Support site to validate that the exact product and feature versions described in this document are supported for your specific environment. The NetApp IMT defines the product components and versions that can be used to construct configurations that are supported by NetApp. Specific results depend on each customer's installation in accordance with published specifications.

*Related information*

https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]
