---
permalink: san-migration/task_fli_transition_importing_the_data.html
sidebar: sidebar
keywords: import, data, fli 7-mode, ontap
summary: "These steps describe how to import the data from a 7-Mode source LUN to an ONTAP destination LUN using FLI."
---
= Importing the data from FLI 7-Mode to ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
These steps describe how to import the data from a 7-Mode source LUN to an ONTAP destination LUN using FLI.

.About this task

Beginning with ONTAP 9.17.1, data migration of foreign LUNs using FLI offline migration is supported with link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html[ASA r2 systems^]. ASA r2 systems vary from other ONTAP systems (ASA, AFF, and FAS) in the implementation of its storage layer.  In ASA r2 systems, volumes are automatically created when a storage unit (LUN or namespace) is created. Each volume contains only one storage unit. Therefore, for ASA r2 systems, you do not need to include the volume name in the  `-path` option when creating the LUN; you should include the storage unit path instead.  

.Steps
. Start the migration import.
+
----
cluster::*> lun import start -vserver fli_72C -path /vol/flivol/72Clun1
----

. Display FLI status.
+
----
cluster::*> lun import show -vserver fli_72C -path /vol/flivol/72Clun1
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
fli_72C D0i1E+G8Wg6m   /vol/flivol/72Clun1 import    started
                                                           completed        100
----
+
If you want to make sure the source LUN remains consistent after the migration completes, you will need to:

 ** After the import show indicates it is completed, shut down the host.
 ** Delete the LUN relationship: `lun import delete -vserver fli_72C -path /vol/flivol/72Clun1`.
+
[NOTE]
====
Remember that after the LUN relationship is broken, the LUNs will quickly lose sync because changes are made to the new LUN only. Therefore, while it may be beneficial to maintain a consistent state in the event you want to restore the original state, the new LUN will likely have changes not reflected in the source LUN.
====
+
[NOTE]
====
After the import is stopped, you can destroy the import relationship unless you intend to verify the import.
====
